const assert = require('node:assert/strict');
const routing = require('../lib/sales-routing');
const { normalizeRecord, buildMetrics, buildOtherChannelsMetrics } = require('../server').__test;
const row = (code, channel, seller, total, date='08/09/2026') => normalizeRecord({'Data Venda':date,'Codigo Reserva':code,Hotel:'SUEDS PLAZA',Canal:channel,Vendedor:seller,'Valor Total':total,Recebido:total,Status:'Confirmada'});
for (const channel of ['BE MOBILE','BE MOBILLE','BOOKING ENGINE','Robo','Airbnb','Booking','Decolar','Expedia']) {
  assert.equal(routing.destination({dataVenda:'01/09/2026',canal:channel}),routing.CHANNELS_SHEET);
  assert.equal(routing.destination({dataVenda:'31/08/2026',canal:channel}),routing.SELLERS_SHEET);
}
assert.equal(routing.classifyDeskhotel('Depto_Reservas - Tatiana Vieira').sellerSale,true);
assert.equal(routing.classifyDeskhotel('BookingCom').channel,'Booking');
assert.equal(routing.classifyDeskhotel('AirBNB').channel,'Airbnb');
assert.throws(()=>routing.classifyDeskhotel(''));
const desk = routing.normalizeDeskhotel({dataVenda:'08/09/2026',origin:'AirBNB',vendedor:'Nome incorreto'});
assert.equal(desk.canal,'Airbnb');
assert.equal(desk.vendedor,'');
assert.equal(desk.fonte,'DESKHOTEL');
assert.equal(desk.targetSheet,routing.CHANNELS_SHEET);
const alice = routing.normalizeDeskhotel({dataVenda:'08/09/2026',origin:'Alice (Assistente Virtual)'});
assert.equal(alice.vendedor,'Alice (Robo)');
assert.equal(alice.formaPagamento,'Cartao credito');
const shortAlice = routing.normalizeDeskhotel({dataVenda:'12/09/2026',origin:'Alice',hotel:'SUEDS CABRALIA',status:'Confirmada'});
assert.equal(shortAlice.canal,'Robo');
assert.equal(shortAlice.vendedor,'Alice (Robo)');
assert.equal(shortAlice.targetSheet,routing.CHANNELS_SHEET);
const shop = routing.normalizeDeskhotel({dataVenda:'11/09/2026',origin:'Depto_Reservas - Loja online',hotel:"Sued's Experiências passeios e transfers",status:'Aprovada'});
assert.equal(shop.hotel,'SUEDS EXPERIENCIAS');
assert.equal(shop.canal,'SITE');
assert.equal(shop.vendedor,'');
assert.equal(shop.targetSheet,routing.CHANNELS_SHEET);
assert.equal(routing.normalizeDeskhotel({dataVenda:'04/09/2026',origin:'Depto_Reservas',hotel:'SUEDS EXPERIENCIAS'}).targetSheet,routing.CHANNELS_SHEET);
const blocked = routing.normalizeDeskhotel({dataVenda:'12/09/2026',origin:'Depto_Reservas - Amanda Sales Melgaço',hotel:'SUEDS PLAZA',status:'Bloqueada'});
assert.equal(blocked.status,'Pendente');
assert.equal(blocked.vendedor,'Amanda Melgaco');
assert.equal(blocked.targetSheet,routing.SELLERS_SHEET);
const kissyla = routing.normalizeDeskhotel({codigo:'CR29070361669',dataVenda:'12/09/2026',origin:'Site_Estabelecimento - Amanda Sales Melgaço',hotel:'SUEDS PLAZA',status:'Confirmada'});
assert.equal(kissyla.canal,'SITE');
assert.equal(kissyla.vendedor,'Amanda Melgaco');
assert.equal(kissyla.targetSheet,routing.SELLERS_SHEET);
assert.equal(routing.normalizeDeskhotel({...kissyla,codigo:'OUTRA'}).targetSheet,routing.SELLERS_SHEET);
const motor = routing.normalizeDeskhotel({dataVenda:'10/09/2026',origin:'Motor - Emanoel Cesar'});
assert.equal(motor.vendedor,'Emanoel Cesar');
assert.equal(motor.canal,'CENTRAL DE RESERVAS');
assert.equal(motor.targetSheet,routing.SELLERS_SHEET);
assert.equal(routing.normalizeDeskhotel({dataVenda:'10/09/2026',origin:'Motor - Alice'}).targetSheet,routing.CHANNELS_SHEET);
assert.equal(routing.normalizeDeskhotel({dataVenda:'08/09/2026',origin:'Depto_Reservas - Tatiana Vieira'}).vendedor,'Tatiana Vieira');
const existingExternal={dataVenda:'08/09/2026',codigo:'CR-A',hotel:'H',canal:'Airbnb',fonte:'DESKHOTEL'};
assert.throws(()=>routing.assertSalesWrite({dataVenda:'08/09/2026',codigo:'CR-A',hotel:'H',canal:'',vendedor:'Rogério Mendes'},routing.SELLERS_SHEET,[existingExternal]),/ja cadastrada/);
assert.throws(()=>routing.assertSalesWrite({dataVenda:'08/09/2026',codigo:'CR-B',hotel:'H',canal:'',vendedor:''},routing.SELLERS_SHEET),/sem vendedor/);
assert.throws(()=>routing.assertSalesWrite({...existingExternal,codigo:'CR-C'},routing.CHANNELS_SHEET),/Origem DeskHotel ausente/);
assert.doesNotThrow(()=>routing.assertSalesWrite({...desk,codigo:'CR-D',hotel:'H'},routing.CHANNELS_SHEET));
assert.doesNotThrow(()=>routing.assertSalesWrite({...alice,codigo:'CR-E',hotel:'H'},routing.CHANNELS_SHEET));
const seller=row('1','CENTRAL DE RESERVAS','Tatiana Vieira',100);
const site=row('2','BE MOBILE','',200);
const robot=row('3','Robo','Alice (Robo)',300);
const airbnb=row('4','Airbnb','',400);
const historical=row('5','BE MOBILE','',500,'31/08/2026');
const period={month:'2026-09',date:'2026-09-09'};
const during=routing.dashboardSources([seller,site,robot,airbnb,historical],[site,robot,airbnb]);
const after=routing.dashboardSources([seller,historical],[site,robot,airbnb]);
const blankDuplicate=row('4','','',400);
assert.deepEqual(routing.dashboardSources([seller,historical,blankDuplicate],[site,robot,airbnb]),after);
assert.deepEqual(during,after);
const alineDeskhotel = row('RES-ALINE','CENTRAL DE RESERVAS','Aline Nunes',750);
alineDeskhotel.source = 'DESKHOTEL';
const alineOmnibees = row('RES-ALINE','Central de Reservas','',750);
alineOmnibees.source = 'OMNIBEES';
const humanSellerDuplicate = routing.dashboardSources([alineDeskhotel],[alineOmnibees]);
assert.equal(humanSellerDuplicate.records.length,1);
assert.equal(humanSellerDuplicate.records[0].seller,'Aline Nunes');
assert.equal(buildMetrics(humanSellerDuplicate.records,[],period).sellers.find(s=>s.name==='Aline Nunes').salesMonth,750);
const metrics=buildMetrics(after.records,[],period);
assert.equal(metrics.channels.find(c=>c.label==='SITE').value,200);
assert.equal(metrics.channels.find(c=>c.label==='Robo').value,300);
assert.equal(metrics.sellers.find(s=>s.name==='Robo').salesMonth,300);
assert.equal(after.otherChannelRecords.filter(r=>r.reservationCode==='3').length,0);
assert.equal(buildMetrics(after.records,[],{month:'2026-08',date:'2026-08-31'}).channels.find(c=>c.label==='SITE').value,500);
assert.equal(buildOtherChannelsMetrics(after.otherChannelRecords,period).channels.find(c=>c.label==='Airbnb').value,400);
const omniAzul = normalizeRecord({'Data Venda':'17/09/2026','Codigo Reserva':'OMNI-AZUL','Hotel':'SUEDS PLAZA','Canal':'Azul Viagens','Valor Total':100,Status:'Confirmada',Fonte:'OMNIBEES'});
const juniperAzul = normalizeRecord({'Data Venda':'17/09/2026','Codigo Reserva':'JUNIPER-ABC123','Hotel':'SUEDS PLAZA','Canal':'Azul Viagens','Valor Total':150,Status:'Confirmada',Fonte:'JUNIPER'});
assert.equal(routing.destination({dataVenda:'17/09/2026',fonte:'JUNIPER',canal:'Azul Viagens'}),routing.CHANNELS_SHEET);
assert.doesNotThrow(()=>routing.assertSalesWrite({dataVenda:'17/09/2026',codigo:'JUNIPER-ABC123',hotel:'SUEDS PLAZA',canal:'Azul Viagens',vendedor:'',fonte:'JUNIPER',status:'Confirmada'},routing.CHANNELS_SHEET));
const azulMetrics = buildOtherChannelsMetrics([omniAzul,juniperAzul],{month:'2026-09',date:'2026-09-17'});
assert.equal(azulMetrics.channels.find(c=>c.label==='Azul Viagens').value,100);
assert.equal(azulMetrics.channels.find(c=>c.label==='Azul Viagens (Via Juniper)').value,150);
assert.equal(azulMetrics.channels.find(c=>c.label==='Azul Viagens Total').value,250);
assert.equal(azulMetrics.totalSales,250);
const augustOmniAzul = normalizeRecord({'Data Venda':'17/08/2026','Codigo Reserva':'OMNI-AUG','Hotel':'SUEDS PLAZA','Canal':'Azul Viagens','Valor Total':100,Status:'Confirmada',Fonte:'OMNIBEES'});
const augustManual = buildOtherChannelsMetrics([augustOmniAzul],{month:'2026-08',date:'2026-08-31'},[['SUEDS PLAZA','200']],[]);
assert.equal(augustManual.channels.find(c=>c.label==='Azul Viagens Total').value,300);
console.log('PASS: September routing, department origins, migration deduplication, Site/Robot metrics and August history.');
