const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
const code = fs.readFileSync(require.resolve('../google-apps-script/importar_carrinhos_niara.gs'), 'utf8');
const written = [];
const range = {setNumberFormat(){return this;}};
const sellers = {name:'Lancamento_Vendas',getLastRow:()=>1,getRange:()=>range};
const channels = {name:'teste lancamento_vendas',getLastRow:()=>1,getRange:()=>range};
const sourceRows = [['Hotel','Reserva'],['Hotel A','same','','31/08/2026','10/09/2026','12/09/2026','Guest',1,100],['Hotel A','same','','01/09/2026','10/09/2026','12/09/2026','Guest',1,200],['Hotel B','same','','02/09/2026','10/09/2026','12/09/2026','Guest',1,300]];
const source = {getLastRow:()=>sourceRows.length,getDataRange:()=>({getValues:()=>sourceRows,getDisplayValues:()=>sourceRows})};
const spreadsheet = {getSheetByName:name=>name==='Site'?source:name===sellers.name?sellers:channels};
const context = vm.createContext({SpreadsheetApp:{getActive:()=>spreadsheet,getUi:()=>({alert(){}}),flush(){}},Date,console});
vm.runInContext(code,context);
context.writeSalesImportRow_=(sheet,row,values)=>written.push({sheet:sheet.name,row,values});
context.findEmptySalesRows_=()=>[written.length+2];
context.importarVendasSite();
assert.deepEqual(written.map(r=>r.sheet),[sellers.name,channels.name,channels.name]);
assert.equal(written[1].values[0],46266);
assert.equal(written[1].values[13],200);
assert.equal(written[1].values[15],'Cartao credito');
assert.equal(written[1].values[4],'');
// Automatic copying keeps historical sales but never reintroduces September rows.
const sale=(date,id)=>[date,id,'Hotel','BE MOBILE','','','','','','','','',10,10,0,'Cartao credito','','Confirmada'];
const automaticRows=[sale('31/08/2026','old'),sale(46266,'new'),sale('02/09/2026','new2')];
channels.getLastRow=()=>automaticRows.length+1;
channels.getRange=()=>({getValues:()=>automaticRows});
context.clearSheetFilterCriteria_=()=>{};
context.organizeSalesSheet_=()=>{};
written.length=0;
assert.equal(context.sincronizarVendasCanaisSiteInterno_(spreadsheet,true).inserted,1);
assert.equal(written[0].values[1],'old');
console.log('PASS: live Apps Script source routes September Site sales, preserves August destination and prevents automatic copies.');
